# Generated by Django 3.2.8 on 2021-10-21 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categry_name',
            new_name='category_name',
        ),
    ]
