# Generated by Django 3.2.8 on 2021-10-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_categry_name_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TimeField(max_length=100),
        ),
    ]
